apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-backstage-plugin-mta-frontend
  namespace: rhdh
  title: MTA Frontend
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/mta
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/mta
  tags: []
spec:
  packageName: "@backstage-community/backstage-plugin-mta-frontend"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-backstage-plugin-mta-frontend:bs_1.49.4__0.4.2!backstage-community-backstage-plugin-mta-frontend
  version: 0.4.2
  backstage:
    role: frontend-plugin
    supportedVersions: 1.49.4
  author: Backstage Community
  support: community
  lifecycle: active
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.backstage-plugin-mta-frontend:
              dynamicRoutes:
                - path: /mta
                  importName: EntityMTAContent
                  menuItem:
                    text: MTA
              mountPoints:
                - mountPoint: entity.page.overview/cards
                  importName: EntityMTAContent
                  config:
                    layout:
                      gridColumnEnd:
                        lg: "span 4"
                        md: "span 6"
                        xs: "span 12"
                    if:
                      allOf:
                        - isKind: component
                        - isType: service
