apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-backstage-plugin-scaffolder-backend-module-mta
  namespace: rhdh
  title: MTA Scaffolder Backend Module
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/mta
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/mta
  tags: []
spec:
  packageName: "@backstage-community/backstage-plugin-scaffolder-backend-module-mta"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-backstage-plugin-scaffolder-backend-module-mta:bs_1.49.4__0.5.1!backstage-community-backstage-plugin-scaffolder-backend-module-mta
  version: 0.5.1
  backstage:
    role: backend-plugin
    supportedVersions: 1.49.4
  author: Backstage Community
  support: community
  lifecycle: active
  appConfigNotRequired: true
  appConfigExamples: []
