apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-backstage-plugin-catalog-backend-module-mta-entity-provider
  namespace: rhdh
  title: MTA Catalog Backend Module Entity Provider
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/mta
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/mta
  tags: []
spec:
  packageName: "@backstage-community/backstage-plugin-catalog-backend-module-mta-entity-provider"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-backstage-plugin-catalog-backend-module-mta-entity-provider:bs_1.49.4__0.4.1!backstage-community-backstage-plugin-catalog-backend-module-mta-entity-provider
  version: 0.4.1
  backstage:
    role: backend-plugin
    supportedVersions: 1.49.4
  author: Backstage Community
  support: community
  lifecycle: active
  appConfigNotRequired: true
  appConfigExamples: []
