apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-search-backend-module-announcements
  namespace: rhdh
  title: Announcements Search Backend Module
  links:
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/announcements
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/announcements
  tags: []
spec:
  packageName: "@backstage-community/plugin-search-backend-module-announcements"
  dynamicArtifact: oci://quay.io/veecode/announcements:bs_1.53.0!backstage-community-plugin-search-backend-module-announcements
  version: 0.19.0
  backstage:
    role: backend-plugin
    supportedVersions: 1.52.0
  author: Backstage Community
  support: community
  lifecycle: active
  appConfigExamples:
    - title: Optional collator schedule
      content:
        search:
          collators:
            announcements:
              schedule:
                frequency:
                  minutes: 30
                initialDelay:
                  seconds: 30
                timeout:
                  minutes: 3
