apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-announcements-backend
  namespace: rhdh
  title: Announcements Backend
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/announcements
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/announcements
  tags: []
spec:
  packageName: "@backstage-community/plugin-announcements-backend"
  dynamicArtifact: oci://quay.io/veecode/announcements:bs_1.53.0!backstage-community-plugin-announcements-backend
  version: 0.26.0
  backstage:
    role: backend-plugin
    supportedVersions: 1.52.0
  author: Backstage Community
  support: community
  lifecycle: active
  appConfigNotRequired: true
  appConfigExamples: []
