apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: pagerduty-backstage-plugin-scaffolder-actions
  namespace: rhdh
  title: "PagerDuty Scaffolder Actions"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/PagerDuty/backstage-plugins
      title: Bugs
    - title: Source Code
      url: https://github.com/PagerDuty/backstage-plugins/tree/main/plugins/backstage-plugin-scaffolder-actions
  annotations:
    backstage.io/source-location: url:https://github.com/PagerDuty/backstage-plugins/tree/main/plugins/backstage-plugin-scaffolder-actions
  tags: []
spec:
  packageName: "@pagerduty/backstage-plugin-scaffolder-actions"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/pagerduty-backstage-plugin-scaffolder-actions:bs_1.49.4__0.2.9!pagerduty-backstage-plugin-scaffolder-actions
  version: 0.2.9
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.49.4
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - pagerduty
  appConfigNotRequired: true
  appConfigExamples: []
