apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-npm-backend
  namespace: rhdh
  title: NPM Backend
  links:
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/npm
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/npm
  tags: []
spec:
  packageName: "@backstage-community/plugin-npm-backend"
  dynamicArtifact: oci://quay.io/veecode/npm:bs_1.49.4!backstage-community-plugin-npm-backend
  version: 1.20.0
  backstage:
    role: backend-plugin
    supportedVersions: 1.49.4
  author: Backstage Community
  support: community
  lifecycle: active
  appConfigExamples:
    - title: Optional registry configuration
      content:
        npm:
          defaultRegistry: ${NPM_DEFAULT_REGISTRY}
          registries:
            - name: private
              url: ${NPM_REGISTRY_URL}
              token: ${NPM_REGISTRY_TOKEN}
