apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: bcp-ctlg-backend-mod-azure-devops-annotator-processor
  namespace: rhdh
  title: "Catalog Backend Module Azure DevOps Annotator Processor"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/azure-devops/plugins/catalog-backend-module-azure-devops-annotator-processor
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/azure-devops/plugins/catalog-backend-module-azure-devops-annotator-processor
  tags:
    - software-catalog
spec:
  packageName: "@backstage-community/plugin-catalog-backend-module-azure-devops-a\
    nnotator-processor"
  dynamicArtifact: oci://quay.io/veecode/azure-devops:bs_1.49.4!backstage-community-plugin-catalog-backend-module-azure-devops-annotator-processor
  version: 0.18.0
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.49.4
  author: Backstage Community
  support: community
  lifecycle: active
  partOf:
    - azure-devops
  appConfigNotRequired: true
  appConfigExamples: []
