apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: proberaum-backstage-plugin-env-viewer
  namespace: rhdh
  title: Env Viewer
  links:
    - url: https://github.com/proberaum/backstage-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/proberaum/backstage-plugins/tree/main/workspaces/env-viewer
  annotations:
    backstage.io/source-location: url:https://github.com/proberaum/backstage-plugins/tree/main/workspaces/env-viewer
  tags: []
spec:
  packageName: "@proberaum/backstage-plugin-env-viewer"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/proberaum-backstage-plugin-env-viewer:bs_1.49.4__0.3.0!proberaum-backstage-plugin-env-viewer
  version: 0.3.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.49.4
  author: Proberaum
  support: community
  lifecycle: active
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            proberaum.backstage-plugin-env-viewer:
              translationResources:
                - importName: envViewerTranslations
                  ref: envViewerTranslationRef
              dynamicRoutes:
                - path: /env-viewer
                  importName: EnvViewerPage
                  menuItem:
                    text: Env viewer
