apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-tekton
  namespace: rhdh
  title: Tekton
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/tekton
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/tekton
  tags: []
spec:
  packageName: '@backstage-community/plugin-tekton'
  dynamicArtifact: oci://quay.io/veecode/tekton:bs_1.53.0!backstage-community-plugin-tekton
  version: 3.37.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.49.4
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - tekton
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-tekton:
              translationResources:
                - importName: tektonTranslations
                  ref: tektonTranslationRef
              mountPoints:
                - mountPoint: entity.page.ci/cards
                  importName: TektonCI
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      allOf:
                        - isTektonCIAvailable
