apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-sonarqube
  namespace: rhdh
  title: "SonarQube Frontend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/sonarqube
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/sonarqube
  tags: []
spec:
  packageName: "@backstage-community/plugin-sonarqube"
  dynamicArtifact: oci://quay.io/veecode/sonarqube:bs_1.53.0!backstage-community-plugin-sonarqube
  version: 1.1.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.49.4
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - sonarqube-catalog-cards
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-sonarqube:
              mountPoints:
                - mountPoint: entity.page.overview/cards
                  importName: EntitySonarQubeCard
                  config:
                    layout:
                      gridColumnEnd:
                        lg: span 4
                        md: span 6
                        xs: span 12
                    if:
                      allOf:
                        - isSonarQubeAvailable
