apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-jenkins
  namespace: rhdh
  title: "Jenkins Frontend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/jenkins
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/jenkins
  tags: []
spec:
  packageName: "@backstage-community/plugin-jenkins"
  dynamicArtifact: oci://quay.io/veecode/jenkins:bs_1.49.4!backstage-community-plugin-jenkins
  version: 0.30.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.49.4
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - jenkins
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-jenkins:
              mountPoints:
                - mountPoint: entity.page.ci/cards
                  importName: EntityJenkinsContent
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      allOf:
                        - isJenkinsAvailable
