apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-analytics-module-matomo
  namespace: rhdh
  title: "Analytics Module Matomo"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/analytics/plugins/analytics-module-matomo
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/analytics/plugins/analytics-module-matomo
  tags: []
spec:
  packageName: "@backstage-community/plugin-analytics-module-matomo"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-analytics-module-matomo:bs_1.49.4__1.27.0!backstage-community-plugin-analytics-module-matomo
  version: 1.27.0
  backstage:
    role: frontend-plugin-module
    supportedVersions: 1.49.4
  author: The Backstage Community
  support: community
  lifecycle: active
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-analytics-module-matomo:
              apiFactories:
                - importName: matomoAnalyticsApi
        app:
          analytics:
            matomo:
              host: ${MATOMO_HOST}
              siteId: ${MATOMO_SITE_ID}
