apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: red-hat-developer-hub-backstage-plugin-homepage-backend
  namespace: rhdh
  title: Homepage Backend
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/homepage
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/homepage
  tags: []
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-homepage-backend"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-homepage-backend:bs_1.49.4__0.1.1!red-hat-developer-hub-backstage-plugin-homepage-backend
  version: 0.1.1
  backstage:
    role: backend-plugin
    supportedVersions: 1.49.4
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
    - home-page
  appConfigExamples:
    - title: Default configuration
      content:
        homepage:
          defaultWidgets:
            - id: rhdh-onboarding-section
              props:
                title: Onboarding section
            - id: rhdh-entity-section
              props:
                title: Entity section
            - id: rhdh-template-section
              props:
                title: Template section
