apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  namespace: rhdh
  name: packages
spec:
  targets:
    - ./apic-backstage-plugin.yaml
    - ./aws-amazon-ecs-plugin-for-backstage-backend.yaml
    - ./aws-amazon-ecs-plugin-for-backstage.yaml
    - ./aws-aws-codebuild-plugin-for-backstage-backend.yaml
    - ./aws-aws-codebuild-plugin-for-backstage.yaml
    - ./aws-aws-codepipeline-plugin-for-backstage-backend.yaml
    - ./aws-aws-codepipeline-plugin-for-backstage.yaml
    - ./aws-aws-s3-catalog-module-for-backstage.yaml
    - ./backstage-community-backstage-plugin-catalog-backend-module-mta-entity-provider.yaml
    - ./backstage-community-backstage-plugin-mta-backend.yaml
    - ./backstage-community-backstage-plugin-mta-frontend.yaml
    - ./backstage-community-backstage-plugin-scaffolder-backend-module-mta.yaml
    - ./backstage-community-plugin-3scale-backend.yaml
    - ./backstage-community-plugin-acr.yaml
    - ./backstage-community-plugin-acs.yaml
    - ./backstage-community-plugin-adr-backend.yaml
    - ./backstage-community-plugin-adr.yaml
    - ./backstage-community-plugin-analytics-module-ga4.yaml
    - ./backstage-community-plugin-analytics-module-matomo.yaml
    - ./backstage-community-plugin-analytics-module-newrelic-browser.yaml
    - ./backstage-community-plugin-analytics-provider-segment.yaml
    - ./backstage-community-plugin-announcements-backend.yaml
    - ./backstage-community-plugin-announcements.yaml
    - ./backstage-community-plugin-argocd-backend.yaml
    - ./backstage-community-plugin-argocd.yaml
    - ./backstage-community-plugin-azure-devops-backend.yaml
    - ./backstage-community-plugin-azure-devops.yaml
    - ./backstage-community-plugin-bookmarks.yaml
    - ./backstage-community-plugin-catalog-backend-module-azure-devops-annotator-processor.yaml
    - ./backstage-community-plugin-catalog-backend-module-keycloak.yaml
    - ./backstage-community-plugin-catalog-backend-module-pingidentity.yaml
    - ./backstage-community-plugin-dynatrace.yaml
    - ./backstage-community-plugin-github-actions.yaml
    - ./backstage-community-plugin-github-deployments.yaml
    - ./backstage-community-plugin-github-discussions.yaml
    - ./backstage-community-plugin-github-issues.yaml
    - ./backstage-community-plugin-github-pull-requests-board.yaml
    - ./backstage-community-plugin-grafana.yaml
    - ./backstage-community-plugin-jenkins-backend.yaml
    - ./backstage-community-plugin-jenkins.yaml
    - ./backstage-community-plugin-jfrog-artifactory.yaml
    - ./backstage-community-plugin-kiali-backend.yaml
    - ./backstage-community-plugin-kiali.yaml
    - ./backstage-community-plugin-lighthouse-backend.yaml
    - ./backstage-community-plugin-lighthouse.yaml
    - ./backstage-community-plugin-mcp-chat-backend.yaml
    - ./backstage-community-plugin-mcp-chat.yaml
    - ./backstage-community-plugin-multi-source-security-viewer-backend.yaml
    - ./backstage-community-plugin-multi-source-security-viewer.yaml
    - ./backstage-community-plugin-nexus-repository-manager.yaml
    - ./backstage-community-plugin-npm-backend.yaml
    - ./backstage-community-plugin-npm.yaml
    - ./backstage-community-plugin-quay-backend.yaml
    - ./backstage-community-plugin-quay.yaml
    - ./backstage-community-plugin-rbac.yaml
    - ./backstage-community-plugin-scaffolder-backend-module-azure-devops.yaml
    - ./backstage-community-plugin-scaffolder-backend-module-dotnet.yaml
    - ./backstage-community-plugin-scaffolder-backend-module-jenkins.yaml
    - ./backstage-community-plugin-scaffolder-backend-module-kubernetes.yaml
    - ./backstage-community-plugin-scaffolder-backend-module-quay.yaml
    - ./backstage-community-plugin-scaffolder-backend-module-regex.yaml
    - ./backstage-community-plugin-scaffolder-backend-module-servicenow.yaml
    - ./backstage-community-plugin-scaffolder-backend-module-sonarqube.yaml
    - ./backstage-community-plugin-search-backend-module-announcements.yaml
    - ./backstage-community-plugin-search-backend-module-azure-devops.yaml
    - ./backstage-community-plugin-search-backend-module-github-discussions.yaml
    - ./backstage-community-plugin-servicenow-backend.yaml
    - ./backstage-community-plugin-servicenow.yaml
    - ./backstage-community-plugin-sonarqube-backend.yaml
    - ./backstage-community-plugin-sonarqube.yaml
    - ./backstage-community-plugin-tech-insights-backend-module-jsonfc.yaml
    - ./backstage-community-plugin-tech-insights-backend.yaml
    - ./backstage-community-plugin-tech-insights-maturity.yaml
    - ./backstage-community-plugin-tech-insights.yaml
    - ./backstage-community-plugin-tech-radar-backend.yaml
    - ./backstage-community-plugin-tech-radar.yaml
    - ./backstage-community-plugin-tekton.yaml
    - ./backstage-community-plugin-todo-backend.yaml
    - ./backstage-community-plugin-todo.yaml
    - ./backstage-community-plugin-topology.yaml
    - ./backstage-community-search-backend-module-adr.yaml
    - ./backstage-plugin-auth.yaml
    - ./backstage-plugin-events-backend-module-gitlab.yaml
    - ./backstage-plugin-mcp-actions-backend.yaml
    - ./backstage-plugin-notifications-backend-module-email.yaml
    - ./backstage-plugin-scaffolder-backend-module-gerrit.yaml
    - ./bcp-ctlg-backend-mod-scaffolder-relation-processor.yaml
    - ./cost-management-backend.yaml
    - ./cost-management.yaml
    - ./devportal-marketplace-backend.yaml
    - ./devportal-marketplace-frontend-dynamic.yaml
    - ./devportal-pending-changes-dynamic.yaml
    - ./dynatrace-backstage-plugin-dql-backend.yaml
    - ./dynatrace-backstage-plugin-dql.yaml
    - ./immobiliarelabs-backstage-plugin-gitlab-backend.yaml
    - ./immobiliarelabs-backstage-plugin-gitlab.yaml
    - ./proberaum-backstage-plugin-config-viewer-backend.yaml
    - ./proberaum-backstage-plugin-config-viewer.yaml
    - ./proberaum-backstage-plugin-env-viewer-backend.yaml
    - ./proberaum-backstage-plugin-env-viewer.yaml
    - ./proberaum-backstage-plugin-github-notifications-backend.yaml
    - ./proberaum-backstage-plugin-icon-viewer.yaml
    - ./red-hat-developer-hub-backstage-plugin-app-auth.yaml
    - ./red-hat-developer-hub-backstage-plugin-app-integrations.yaml
    - ./red-hat-developer-hub-backstage-plugin-bulk-import-backend.yaml
    - ./red-hat-developer-hub-backstage-plugin-bulk-import.yaml
    - ./red-hat-developer-hub-backstage-plugin-dynamic-home-page.yaml
    - ./red-hat-developer-hub-backstage-plugin-global-header.yaml
    - ./red-hat-developer-hub-backstage-plugin-homepage-backend.yaml
    - ./red-hat-developer-hub-backstage-plugin-konflux-backend.yaml
    - ./red-hat-developer-hub-backstage-plugin-konflux.yaml
    - ./red-hat-developer-hub-backstage-plugin-qe-theme.yaml
    - ./red-hat-developer-hub-backstage-plugin-scaffolder-backend-module-x2a.yaml
    - ./red-hat-developer-hub-backstage-plugin-scaffolder-mcp-extras.yaml
    - ./red-hat-developer-hub-backstage-plugin-software-catalog-mcp-extras.yaml
    - ./red-hat-developer-hub-backstage-plugin-techdocs-mcp-extras.yaml
    - ./red-hat-developer-hub-backstage-plugin-theme.yaml
    - ./red-hat-developer-hub-backstage-plugin-translations-backend.yaml
    - ./red-hat-developer-hub-backstage-plugin-translations.yaml
    - ./red-hat-developer-hub-backstage-plugin-x2a-backend.yaml
    - ./red-hat-developer-hub-backstage-plugin-x2a-dcr.yaml
    - ./red-hat-developer-hub-backstage-plugin-x2a-mcp-extras.yaml
    - ./red-hat-developer-hub-backstage-plugin-x2a.yaml
    - ./rhdh-backstage-plugin-scorecard-backend-module-dependabot.yaml
    - ./rhdh-backstage-plugin-scorecard-backend-module-filecheck.yaml
    - ./rhdh-backstage-plugin-scorecard-backend-module-github.yaml
    - ./rhdh-backstage-plugin-scorecard-backend-module-jira.yaml
    - ./rhdh-backstage-plugin-scorecard-backend-module-openssf.yaml
    - ./rhdh-backstage-plugin-scorecard-backend-module-sonarqube.yaml
    - ./rhdh-backstage-plugin-scorecard-backend.yaml
    - ./rhdh-backstage-plugin-scorecard.yaml
    - ./rhdh-bs-plugin-catalog-backend-module-model-catalog.yaml
    - ./rhdh-bs-plugin-catalog-techdoc-url-reader-backend.yaml
    - ./rhdh-bsp-adoption-insights-backend.yaml
    - ./rhdh-bsp-adoption-insights.yaml
    - ./rhdh-bsp-analytics-mod-adoption-insights.yaml
    - ./rhdh-bsp-ctlg-backend-mod-extensions.yaml
    - ./rhdh-bsp-extensions.yaml
    - ./rhdh-bsp-global-floating-action-button.yaml
    - ./rhdh-bsp-lightspeed-backend.yaml
    - ./rhdh-bsp-lightspeed.yaml
    - ./rhdh-bsp-orchestrator-backend-mod-loki.yaml
    - ./rhdh-bsp-orchestrator-backend.yaml
    - ./rhdh-bsp-orchestrator-form-widgets.yaml
    - ./rhdh-bsp-orchestrator.yaml
    - ./rhdh-bsp-quickstart.yaml
    - ./rhdh-bsp-scaffolder-backend-mod-orchestrator.yaml
    - ./roadiehq-backstage-plugin-argo-cd-backend.yaml
    - ./roadiehq-backstage-plugin-argo-cd.yaml
    - ./roadiehq-backstage-plugin-datadog.yaml
    - ./roadiehq-backstage-plugin-github-insights.yaml
    - ./roadiehq-backstage-plugin-github-pull-requests.yaml
    - ./roadiehq-backstage-plugin-iframe.yaml
    - ./roadiehq-backstage-plugin-jira.yaml
    - ./roadiehq-backstage-plugin-security-insights.yaml
    - ./roadiehq-scaffolder-backend-argocd.yaml
    - ./roadiehq-scaffolder-backend-module-aws.yaml
    - ./roadiehq-scaffolder-backend-module-http-request.yaml
    - ./roadiehq-scaffolder-backend-module-utils.yaml
    - ./veecode-platform-backstage-plugin-catalog-backend-module-ai-resources.yaml
    - ./veecode-platform-backstage-plugin-github-workflows-backend.yaml
    - ./veecode-platform-backstage-plugin-github-workflows.yaml
    - ./veecode-platform-plugin-veecode-homepage.yaml
    - ./veecode-platform-plugin-veecode-theme.yaml
    - ./vertigo-platform-plugin-vertigo-theme.yaml
