apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-kiali-backend
  namespace: rhdh
  title: 'Kiali Backend'
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/kiali
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/kiali
  tags:
    - software-catalog
spec:
  packageName: "@backstage-community/plugin-kiali-backend"
  dynamicArtifact: oci://quay.io/veecode/kiali:bs_1.49.4!backstage-community-plugin-kiali-backend
  version: 1.29.1
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.49.4
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - kiali
  appConfigExamples:
    - title: Default configuration
      content:
        kiali:
          providers:
            - name: kiali
              url: '${KIALI_ENDPOINT}'
              skipTLSVerify: true
              serviceAccountToken: '${KIALI_SERVICE_ACCOUNT_TOKEN}'
              sessionTime: 60
