apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-scaffolder-backend-module-servicenow
  namespace: rhdh
  title: "Scaffolder Backend Module ServiceNow"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/scaffolder-backend-module-servicenow
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/scaffolder-backend-module-servicenow
  tags:
    - software-templates
spec:
  packageName: "@backstage-community/plugin-scaffolder-backend-module-servicenow"
  # Tag: 1.10.0--2.11.0, Build date: 2026-01-29T16:10:04Z
  dynamicArtifact: "oci://quay.io/veecode/scaffolder-backend-module-servicenow:bs_1.49.4!backstage-community-plugin-scaffolder-backend-module-servicenow"
  version: 2.15.1
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.49.4
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - servicenow-scaffolder-actions
  appConfigExamples:
    - title: Default configuration
      content:
        servicenow:
          baseUrl: ${SERVICENOW_BASE_URL}
          username: ${SERVICENOW_USERNAME}
          password: ${SERVICENOW_PASSWORD}
