apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-scaffolder-backend-module-github
  namespace: rhdh
  title: "Scaffolder Backend Module GitHub"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend-module-github
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend-module-github
  tags:
    - software-templates
spec:
  packageName: "@backstage/plugin-scaffolder-backend-module-github"
  # Tag: bs_1.52.0__0.9.10
  dynamicArtifact: "oci://quay.io/veecode/backstage-plugin-scaffolder-backend-module-github@sha256:07d86f89b7ee985e2ea793710de444866197e2daad46213c999a5e05157b7b48"
  version: 0.9.10
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.52.0
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - github-scaffolder-actions
  appConfigNotRequired: true
  appConfigExamples: []
