apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-scaffolder-backend-module-quay
  namespace: rhdh
  title: "Scaffolder Backend Module Quay"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should
        raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/quay
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/quay
  tags:
    - software-templates
spec:
  packageName: "@backstage-community/plugin-scaffolder-backend-module-quay"
  dynamicArtifact: oci://quay.io/veecode/quay:bs_1.49.4!backstage-community-plugin-scaffolder-backend-module-quay
  version: 2.18.0
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.49.4
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - quay-scaffolder-actions
  appConfigNotRequired: true
  appConfigExamples: []
