apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-catalog-backend-module-msgraph
  namespace: rhdh
  title: "Catalog Backend Module MS Graph"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-msgraph
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-msgraph
  tags:
    - software-catalog
spec:
  packageName: "@backstage/plugin-catalog-backend-module-msgraph"
  # Tag: bs_1.52.0__0.10.3
  dynamicArtifact: "oci://quay.io/veecode/backstage-plugin-catalog-backend-module-msgraph@sha256:4e35f3c39026325949be60af2a9b0e04938de87a3e1e8d6caff8a0bc9ccb80b2"
  version: 0.10.3
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.52.0
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - microsoft-graph-catalog-integration
  appConfigExamples:
    - title: Default configuration
      content:
        catalog:
          providers:
            microsoftGraphOrg:
              providerId:
                target: https://graph.microsoft.com/v1.0
                tenantId: ${MICROSOFT_TENANT_ID}
                clientId: ${MICROSOFT_CLIENT_ID}
                clientSecret: ${MICROSOFT_CLIENT_SECRET}
                schedule:
                  frequency:
                    minutes: 60
                  initialDelay:
                    seconds: 15
                  timeout:
                    minutes: 15
