apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-kubernetes
  namespace: rhdh
  title: "Kubernetes Frontend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/kubernetes
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/kubernetes
  tags: []
spec:
  packageName: "@backstage/plugin-kubernetes"
  # Tag: bs_1.52.0__0.12.20
  dynamicArtifact: "oci://quay.io/veecode/backstage-plugin-kubernetes@sha256:fd94026e0650a4992ecc8ff0cdaf1f515c644fc1b6373b7bff812243e81fd76f"
  version: 0.12.20
  backstage:
    role: frontend-plugin
    supportedVersions: 1.52.0
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - kubernetes
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage.plugin-kubernetes:
              mountPoints:
                - mountPoint: entity.page.kubernetes/cards
                  importName: EntityKubernetesContent
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      anyOf:
                        - hasAnnotation: backstage.io/kubernetes-id
                        - hasAnnotation: backstage.io/kubernetes-namespace
