apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: rhdh-bs-plugin-catalog-techdoc-url-reader-backend
  namespace: rhdh
  title: "@red-hat-developer-hub/backstage-plugin-catalog-techdoc-url-reader-backend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/ai-integrations/plugins/catalog-techdoc-url-reader-backend
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/ai-integrations/plugins/catalog-techdoc-url-reader-backend
  tags: []
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-catalog-techdoc-url-reader-backend"
  dynamicArtifact: oci://quay.io/veecode/ai-integrations:bs_1.49.4!red-hat-developer-hub-backstage-plugin-catalog-techdoc-url-reader-backend
  version: 0.5.0
  backstage:
    role: backend-plugin
    supportedVersions: 1.49.4
  author: Backstage
  support: dev-preview
  lifecycle: active
  partOf:
    - ai-integrations
  appConfigExamples:
    - title: Default configuration
      content:
        catalog:
          providers:
            modelCatalog:
              developement:
                baseUrl: http://localhost:9090
