apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: roadiehq-scaffolder-backend-module-http-request
  namespace: rhdh
  title: "Scaffolder Backend Module HTTP Request"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/RoadieHQ/roadie-backstage-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/scaffolder-actions/scaffolder-backend-module-http-request
  annotations:
    backstage.io/source-location: url:https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/scaffolder-actions/scaffolder-backend-module-http-request
  tags:
    - software-templates
spec:
  packageName: "@roadiehq/scaffolder-backend-module-http-request"
  # Tag: bs_1.52.0__5.6.0
  dynamicArtifact: "oci://quay.io/veecode/roadiehq-scaffolder-backend-module-http-request@sha256:f97ccbf39855e16b1eaedbd580990f8b9e3725f041598641c5c2fca25538c627"
  version: 5.6.0
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.49.4
    author: Roadie
  support: generally-available
  lifecycle: active
  partOf:
    - http-request-scaffolder-action
  appConfigNotRequired: true
  appConfigExamples: []
