apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-tech-insights-backend-module-jsonfc
  namespace: rhdh
  title: "Tech Insights Backend Module Jsonfc"
  links:
  - url: https://red.ht/rhdh
    title: Homepage
  - url: https://github.com/backstage/community-plugins/issues
    title: Bugs
  - title: Source Code
    url: https://github.com/backstage/community-plugins/tree/main/workspaces/tech-insights
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/tech-insights
  tags: []
spec:
  packageName: '@backstage-community/plugin-tech-insights-backend-module-jsonfc'
  dynamicArtifact: oci://ghcr.io/veecode-platform/devportal-plugin-export-overlays/tech-insights:bs_1.49.4!backstage-community-plugin-tech-insights-backend-module-jsonfc
  version: 0.7.0
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.47.2
  author: VeeCode
  support: community
  lifecycle: active
  partOf:
  - tech-insights
