apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: rhdh-bs-plugin-kserve-kubeflow-connector-backend
  namespace: rhdh
  title: "@red-hat-developer-hub/backstage-plugin-kserve-kubeflow-connector-backend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/ai-integrations/plugins/kserve-kubeflow-connector-backend
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/ai-integrations/plugins/kserve-kubeflow-connector-backend
  tags: []
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-kserve-kubeflow-connector-backend"
  dynamicArtifact: oci://quay.io/veecode/ai-integrations:bs_1.52.0!red-hat-developer-hub-backstage-plugin-kserve-kubeflow-connector-backend
  version: 0.1.1
  backstage:
    role: backend-plugin
    supportedVersions: 1.52.0
  author: Backstage
  support: dev-preview
  lifecycle: active
  partOf:
    - ai-integrations
  appConfigExamples:
    - title: Default configuration
      content:
        catalog:
          providers:
            modelCatalog:
              developement:
                my-cluster:
                  kubernetesPluginRef: ${K8S_CLUSTER_NAME}
                  kubeflow-model-catalog-url: http://localhost:9090
        kubernetes:
          serviceLocatorMethod:
            type: multiTenant
          clusterLocatorMethods:
            - type: config
              clusters:
                - name: ${K8S_CLUSTER_NAME}
                  url: ${K8S_CLUSTER_URL}
                  authProvider: serviceAccount
                  skipTLSVerify: true
                  serviceAccountToken: ${K8S_CLUSTER_TOKEN}
