apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-kiali
  namespace: rhdh
  title: "Kiali"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/kiali
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/kiali
  tags:
    - software-catalog
spec:
  packageName: "@backstage-community/plugin-kiali"
  dynamicArtifact: oci://quay.io/veecode/kiali:bs_1.49.4!backstage-community-plugin-kiali
  version: 1.50.2
  backstage:
    role: frontend-plugin
    supportedVersions: 1.49.4
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - kiali
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-kiali:
              appIcons:
                - importName: KialiIcon
                  name: kialiIcon
              dynamicRoutes:
                - importName: KialiPage
                  menuItem:
                    icon: kialiIcon
                    text: Kiali
                  path: /kiali
              mountPoints:
                - config:
                    if:
                      anyOf:
                        - hasAnnotation: backstage.io/kubernetes-namespace
                  importName: EntityKialiContent
                  mountPoint: entity.page.kiali/cards
