apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: proberaum-backstage-plugin-config-viewer-backend
  namespace: rhdh
  title: Config Viewer Backend
  links:
    - url: https://github.com/proberaum/backstage-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/proberaum/backstage-plugins/tree/main/workspaces/config-viewer
  annotations:
    backstage.io/source-location: url:https://github.com/proberaum/backstage-plugins/tree/main/workspaces/config-viewer
  tags: []
spec:
  packageName: "@proberaum/backstage-plugin-config-viewer-backend"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/proberaum-backstage-plugin-config-viewer-backend:bs_1.49.4__0.13.0!proberaum-backstage-plugin-config-viewer-backend
  version: 0.13.0
  backstage:
    role: backend-plugin
    supportedVersions: 1.49.4
  author: Proberaum
  support: community
  lifecycle: active
  appConfigExamples:
    - title: Minimal configuration
      content:
        configViewer:
          files:
            - ${CONFIG_VIEWER_APP_CONFIG_FILES}
