apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-adr-backend
  namespace: rhdh
  title: ADR Backend
  links:
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/adr
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/adr
  tags: []
spec:
  packageName: "@backstage-community/plugin-adr-backend"
  dynamicArtifact: oci://quay.io/veecode/adr:bs_1.53.0!backstage-community-plugin-adr-backend
  version: 0.23.0
  backstage:
    role: backend-plugin
    supportedVersions: 1.52.0
  author: Backstage Community
  support: community
  lifecycle: active
  appConfigNotRequired: true
  appConfigExamples: []
