apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: roadiehq-backstage-plugin-datadog
  namespace: rhdh
  title: "Datadog"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/RoadieHQ/roadie-backstage-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/frontend/backstage-plugin-datadog
  annotations:
    backstage.io/source-location: url:https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/frontend/backstage-plugin-datadog
  tags: []
spec:
  packageName: "@roadiehq/backstage-plugin-datadog"
  dynamicArtifact: oci://quay.io/veecode/roadie-backstage-plugins:bs_1.54.0-next.0!roadiehq-backstage-plugin-datadog
  nfs:
    entrypoint: ./alpha
    exposedModules:
      - .
      - alpha
    composition:
      route: /catalog/default/component/probe-roadie-backstage-plugins
      featureId: datadog.datadog-graph
      probe:
        kind: Component
        annotations:
          datadoghq.com/graph-token: drydock/probe
      provenance:
        sources:
          - path: plugins/frontend/backstage-plugin-datadog/src/alpha.ts
            lines: 13-21
          - path: plugins/frontend/backstage-plugin-datadog/src/alpha/entityCards.tsx
            lines: 7-14
          - path: plugins/frontend/backstage-plugin-datadog/src/components/GraphWidget.tsx
            lines: 1-99
          - path: plugins/frontend/backstage-plugin-datadog/src/components/GraphWidget.tsx
            lines: 62-62
          - path: plugins/frontend/backstage-plugin-datadog/src/plugin.ts
            lines: 18-25
          - path: plugins/frontend/backstage-plugin-datadog/src/components/useDatadogAppData.ts
            lines: 20-20
      assertions:
        - type: text
          value: Datadog Graph
  version: 2.7.2
  backstage:
    role: frontend-plugin
    supportedVersions: 1.49.4
  author: Roadie
  support: community
  lifecycle: active
  partOf:
    - datadog
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            roadiehq.backstage-plugin-datadog:
              mountPoints:
                - mountPoint: entity.page.monitoring/cards
                  importName: EntityDatadogContent
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      allOf:
                        - isDatadogAvailable
