apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-notifications-backend
  namespace: rhdh
  title: "Notifications Backend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/notifications-backend
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/notifications-backend
  tags: []
spec:
  packageName: "@backstage/plugin-notifications-backend"
  dynamicArtifact: oci://quay.io/veecode/backstage:bs_1.52.0!backstage-plugin-notifications-backend
  version: 0.6.6
  backstage:
    role: backend-plugin
    supportedVersions: 1.52.0
  author: Red Hat
  support: tech-preview
  lifecycle: active
  appConfigExamples:
    - title: Default configuration
      content:
        notifications:
          concurrencyLimit: 10
  partOf:
    - notifications
