apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-app-visualizer
  namespace: rhdh
  title: "App Visualizer"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/app-visualizer
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/app-visualizer
  tags: []
spec:
  packageName: "@backstage/plugin-app-visualizer"
  dynamicArtifact: oci://quay.io/veecode/backstage:bs_1.52.0!backstage-plugin-app-visualizer
  version: 0.2.5
  backstage:
    role: frontend-plugin
    supportedVersions: 1.52.0
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - app-visualizer
  appConfigNotRequired: true
  appConfigExamples: []
