apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-scaffolder-backend-module-bitbucket-cloud
  namespace: rhdh
  title: "Scaffolder Backend Module Bitbucket Cloud"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend-module-bitbucket-cloud
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend-module-bitbucket-cloud
  tags:
    - software-templates
spec:
  packageName: "@backstage/plugin-scaffolder-backend-module-bitbucket-cloud"
  dynamicArtifact: oci://quay.io/veecode/backstage:bs_1.52.0!backstage-plugin-scaffolder-backend-module-bitbucket-cloud
  version: 0.3.7
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.52.0
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - bitbucket-cloud-scaffolder-actions
  appConfigNotRequired: true
  appConfigExamples: []
