apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-notifications-backend-module-email
  namespace: rhdh
  title: "Notifications Backend Module Email"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/notifications-backend-module-email
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/notifications-backend-module-email
  tags: []
spec:
  packageName: "@backstage/plugin-notifications-backend-module-email"
  dynamicArtifact: oci://quay.io/veecode/backstage:bs_1.49.4!backstage-plugin-notifications-backend-module-email
  version: 0.3.23
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.48.4
  author: VeeCode
  support: tech-preview
  lifecycle: active
  partOf:
    - notifications-email
  appConfigExamples:
    - title: Default configuration
      content:
        notifications:
          processors:
            email:
              transportConfig:
                transport: smtp
                hostname: ${EMAIL_HOSTNAME}
                port: 587
                username: ${EMAIL_USERNAME}
                password: ${EMAIL_PASSWORD}
              sender: ${EMAIL_SENDER}
              broadcastConfig:
                receiver: users
