apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: rhdh-backstage-plugin-scorecard-backend-module-dependabot
  namespace: rhdh
  title: "Scorecard Backend Module for Dependabot"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/scorecard/plugins/scorecard-backend-module-dependabot
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/scorecard/plugins/scorecard-backend-module-dependabot
  tags:
    - analytics
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-scorecard-backend-module-dependabot"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-scorecard-backend-module-dependabot:bs_1.49.4__0.2.11!red-hat-developer-hub-backstage-plugin-scorecard-backend-module-dependabot
  version: 0.2.11
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.49.4
  author: Red Hat
  support: dev-preview
  lifecycle: active
  partOf:
    - scorecard
  appConfigNotRequired: true
  appConfigExamples: []
