apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: rhdh-backstage-plugin-scorecard-backend-module-sonarqube
  namespace: rhdh
  title: "Scorecard Backend Module for SonarQube"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/scorecard/plugins/scorecard-backend-module-sonarqube
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/scorecard/plugins/scorecard-backend-module-sonarqube
  tags:
    - analytics
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-scorecard-backend-module-sonarqube"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-scorecard-backend-module-sonarqube:bs_1.49.4__0.1.6!red-hat-developer-hub-backstage-plugin-scorecard-backend-module-sonarqube
  version: 0.1.6
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.49.4
  author: Red Hat
  support: dev-preview
  lifecycle: active
  partOf:
    - scorecard
  appConfigExamples:
    - title: Default SonarCloud configuration
      content:
        sonarqube:
          baseUrl: https://sonarcloud.io
          apiKey: ${SONARQUBE_API_KEY}
    - title: Named instances configuration
      content:
        sonarqube:
          instances:
            - name: my-sonarqube
              baseUrl: https://sonarqube.example.com
              apiKey: ${SONARQUBE_API_KEY}
              authType: Basic
