apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: rhdh-backstage-plugin-scorecard
  namespace: rhdh
  title: "Scorecard"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/scorecard/plugins/scorecard
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/scorecard/plugins/scorecard
  tags:
    - analytics
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-scorecard"
  dynamicArtifact: oci://quay.io/veecode/scorecard:bs_1.49.4!red-hat-developer-hub-backstage-plugin-scorecard
  version: 2.7.8
  backstage:
    role: frontend-plugin
    supportedVersions: 1.49.4
  author: Red Hat
  support: dev-preview
  lifecycle: active
  partOf:
    - scorecard
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            red-hat-developer-hub.backstage-plugin-scorecard:
              translationResources:
                - importName: scorecardTranslations
                  ref: scorecardTranslationRef
              dynamicRoutes:
                - path: /scorecard/aggregations/:aggregationId/metrics/:metricId
                  importName: ScorecardPage
              entityTabs:
                - path: "/scorecard"
                  title: Scorecard
                  mountPoint: entity.page.scorecard
              mountPoints:
                - mountPoint: entity.page.scorecard/cards
                  importName: EntityScorecardContent
                  config:
                    layout:
                      gridColumn: 1 / -1
                  if:
                    allOf:
                      - isKind: component
    - title: Optional GitHub Scorecard configuration for read-only Homepage
      content:
        dynamicPlugins:
          frontend:
            red-hat-developer-hub.backstage-plugin-scorecard:
              - mountPoint: home.page/cards
                importName: ScorecardHomepageCard
                config:
                  props:
                    aggregationId: "github.open_prs"
                  layouts:
                    xl: { w: 3, h: 6, x: 3 }
                    lg: { w: 4, h: 6, x: 4 }
                    md: { w: 6, h: 6, x: 6 }
                    sm: { w: 12, h: 6 }
                    xs: { w: 12, h: 6 }
                    xxs: { w: 12, h: 6 }
    - title: Optional GitHub Scorecard configuration for customizable Homepage
      content:
        dynamicPlugins:
          frontend:
            red-hat-developer-hub.backstage-plugin-scorecard:
              - mountPoint: home.page/cards
                importName: ScorecardHomepageCard
                config:
                  id: "scorecard-github.open_prs"
                  title: "GitHub open PRs"
                  props:
                    aggregationId: "github.open_prs"
    - title: Optional GitHub Scorecard custom KPI configuration for customizable Homepage
      content:
        dynamicPlugins:
          frontend:
            red-hat-developer-hub.backstage-plugin-scorecard:
              - mountPoint: home.page/cards
                importName: ScorecardHomepageCard
                config:
                  id: "scorecard-github.open_prs_weighted_kpi"
                  title: "GitHub Open PRs (weighted health)"
                  props:
                    aggregationId: "openPrsWeightedKpi" # Ensure the definition is under `scorecard.aggregationKPIs.<aggregationId>`
    - title: Optional Jira Scorecard configuration for read-only Homepage
      content:
        dynamicPlugins:
          frontend:
            red-hat-developer-hub.backstage-plugin-scorecard:
              - mountPoint: home.page/cards
                importName: ScorecardHomepageCard
                config:
                  props:
                    aggregationId: "jira.open_issues"
                  layouts:
                    xl: { w: 3, h: 6 }
                    lg: { w: 4, h: 6 }
                    md: { w: 6, h: 6 }
                    sm: { w: 12, h: 6 }
                    xs: { w: 12, h: 6 }
                    xxs: { w: 12, h: 6 }
    - title: Optional Jira Scorecard configuration for customizable Homepage
      content:
        dynamicPlugins:
          frontend:
            red-hat-developer-hub.backstage-plugin-scorecard:
              - mountPoint: home.page/cards
                importName: ScorecardHomepageCard
                config:
                  id: "scorecard-jira.open_issues"
                  title: "Jira open tickets"
                  props:
                    aggregationId: "jira.open_issues"
    - title: Optional Filecheck Scorecard custom KPI configuration for customizable Homepage
      content:
        dynamicPlugins:
          frontend:
            red-hat-developer-hub.backstage-plugin-scorecard:
              - mountPoint: home.page/cards
                importName: ScorecardHomepageCard
                config:
                  id: "scorecard-filecheck.license"
                  title: "Scorecard: LICENSE file exists"
                  props:
                    aggregationId: "licenseFileExistsKpi" # Ensure the definition is under `scorecard.aggregationKPIs.<aggregationId>`
