apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: rhdh-backstage-plugin-scorecard-backend-module-github
  namespace: rhdh
  title: "Scorecard Backend Module for GitHub"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/scorecard/plugins/scorecard-backend-module-github
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/scorecard/plugins/scorecard-backend-module-github
  tags:
    - analytics
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-scorecard-backend-module-github"
  dynamicArtifact: oci://quay.io/veecode/scorecard:bs_1.49.4!red-hat-developer-hub-backstage-plugin-scorecard-backend-module-github
  version: 2.7.7
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.49.4
  author: Red Hat
  support: dev-preview
  lifecycle: active
  partOf:
    - scorecard
  appConfigExamples:
    - title: Optional GitHub open-PR scorecard schedule
      content:
        scorecard:
          plugins:
            github:
              open_prs:
                schedule:
                  frequency: { hours: 4 }
                  timeout: { minutes: 10 }
