apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-redhat-argocd
  namespace: rhdh
  title: ArgoCD
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/argocd
  annotations:
    backstage.io/source-location: url https://github.com/backstage/community-plugins/tree/main/workspaces/argocd
  tags: []
spec:
  packageName: "@backstage-community/plugin-argocd"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-argocd:bs_1.53.0__2.10.0!backstage-community-plugin-argocd
  version: 2.10.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.45.3
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - redhat-argocd
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-argocd:
              translationResources:
                - importName: argocdTranslations
                  module: Alpha
                  ref: argocdTranslationRef
              mountPoints:
                - mountPoint: entity.page.overview/cards
                  importName: ArgocdDeploymentSummary
                  config:
                    layout:
                      gridColumnEnd:
                        lg: span 8
                        xs: span 12
                    if:
                      allOf:
                        - isArgocdConfigured
                - mountPoint: entity.page.cd/cards
                  importName: ArgocdDeploymentLifecycle
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      allOf:
                        - isArgocdConfigured
