apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: immobiliarelabs-backstage-plugin-gitlab-backend
  namespace: rhdh
  title: "GitLab Backend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/immobiliare/backstage-plugin-gitlab/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/immobiliare/backstage-plugin-gitlab/tree/main/packages/gitlab-backend
  annotations:
    backstage.io/source-location: url:https://github.com/immobiliare/backstage-plugin-gitlab/tree/main/packages/gitlab-backend
  tags: []
spec:
  packageName: "@immobiliarelabs/backstage-plugin-gitlab-backend"
  dynamicArtifact: oci://quay.io/veecode/gitlab:bs_1.49.4!immobiliarelabs-backstage-plugin-gitlab-backend
  version: 7.0.1
  backstage:
    role: backend-plugin
    supportedVersions: 1.48.3
  author: VeeCode
  support: community
  lifecycle: active
  partOf:
    - backstage-catalog-cards
  appConfigExamples:
    - title: Default configuration
      content:
        gitlab:
          host: ${GITLAB_HOST}
          token: ${GITLAB_TOKEN}
