#!/bin/bash
#
# Generates catalog-entities/dynamic-plugins.default.yaml from the
# spec.dynamicArtifact field of every Package entity under
# workspaces/*/metadata/*.yaml — Option D step 1 (see devportal-planning
# docs/milestones/M3.md, Q9/Q10).
#
# The committed dynamic-plugins.default.yaml stays a stub in git; this
# script overwrites it in the *working tree* only, at CI assemble time,
# exactly like catalog-entities/extensions/packages/ is already assembled
# from the same source by assemble-catalog-index.sh. Nothing here gets
# committed back.
#
# Only Package entities whose dynamicArtifact starts with `oci://` are
# emitted — those are the ones {{inherit}} can resolve from
# CATALOG_INDEX_IMAGE. The remaining npm-style
# `./dynamic-plugins/dist/...` refs (community packages built inline by
# their own workspace) have no OCI coordinate to pin here and are skipped.
#
# Every entry is written `disabled: true` on purpose: this index only
# declares canonical versions for {{inherit}} to resolve. Enabling a
# plugin for a given tenant/operator stays their job, in their own
# dynamic-plugins.yaml.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT="$REPO_ROOT/catalog-entities/dynamic-plugins.default.yaml"

NO_DIGEST=false
for arg in "$@"; do
  case "$arg" in
    --no-digest) NO_DIGEST=true ;;
    *)
      echo "ERROR: unknown argument: $arg" >&2
      exit 1
      ;;
  esac
done

echo "Generating dynamic-plugins.default.yaml from workspaces/*/metadata..."

# Collect one dynamicArtifact value per metadata file, oci:// ones only,
# stripping optional surrounding quotes.
raw_refs=()
for metadata_file in "$REPO_ROOT"/workspaces/*/metadata/*.yaml; do
  [ -f "$metadata_file" ] || continue
  line="$(grep -m1 -E '^\s*dynamicArtifact:' "$metadata_file" || true)"
  [ -n "$line" ] || continue

  value="${line#*dynamicArtifact:}"
  value="$(printf '%s' "$value" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"
  value="$(printf '%s' "$value" | sed -E 's/^"(.*)"$/\1/; s/^'"'"'(.*)'"'"'$/\1/')"

  case "$value" in
    oci://*) raw_refs+=("$value") ;;
    *) ;; # non-OCI (npm-style dynamic-plugins/dist path) — nothing to pin here
  esac
done

if [ "${#raw_refs[@]}" -eq 0 ]; then
  echo "ERROR: found zero oci:// dynamicArtifact refs under workspaces/*/metadata — refusing to generate an empty index" >&2
  exit 1
fi

# Dedupe identical full refs (same image, tag AND selector can appear more
# than once, e.g. shared metadata files).
mapfile -t refs < <(printf '%s\n' "${raw_refs[@]}" | sort -u)

# First pass: count unique image:tag coordinates regardless of digest mode,
# for the summary line.
declare -A SEEN_IMAGE_TAG
unique_images=0
for ref in "${refs[@]}"; do
  rest="${ref#oci://}"
  image_tag="${rest%%!*}"
  if [ -z "${SEEN_IMAGE_TAG[$image_tag]+x}" ]; then
    SEEN_IMAGE_TAG[$image_tag]=1
    unique_images=$((unique_images + 1))
  fi
done

declare -A DIGEST_CACHE
output_entries=()
for ref in "${refs[@]}"; do
  rest="${ref#oci://}"
  image_tag="${rest%%!*}"
  selector="${rest#*!}"
  image="${image_tag%%:*}"
  tag="${image_tag#*:}"

  if [ "$NO_DIGEST" = true ]; then
    output_entries+=("\"oci://${image_tag}!${selector}\"")
    continue
  fi

  if [ -z "${DIGEST_CACHE[$image_tag]+x}" ]; then
    if ! command -v skopeo >/dev/null 2>&1; then
      echo "ERROR: skopeo is required to resolve digests (or pass --no-digest for a local dry-run)" >&2
      exit 1
    fi
    digest="$(skopeo inspect --format '{{.Digest}}' "docker://${image_tag}" 2>&1)" \
      || { echo "ERROR: failed to resolve digest for ${image_tag}: ${digest}" >&2; exit 1; }
    case "$digest" in
      sha256:*) ;;
      *) echo "ERROR: unexpected digest output for ${image_tag}: ${digest}" >&2; exit 1 ;;
    esac
    DIGEST_CACHE[$image_tag]="$digest"
  fi

  digest="${DIGEST_CACHE[$image_tag]}"
  output_entries+=("\"oci://${image}@${digest}!${selector}\" # was :${tag}")
done

# Deterministic ordering, sorted by the package ref itself.
mapfile -t sorted_entries < <(printf '%s\n' "${output_entries[@]}" | sort)

{
  echo "# GENERATED by scripts/generate-dpdy-index.sh from workspaces/*/metadata/*.yaml."
  echo "# Do not hand-edit. Regenerated at CI assemble time by"
  echo "# scripts/assemble-catalog-index.sh; the version committed to git is a stub"
  echo "# (see devportal-planning docs/milestones/M3.md, Q9/Q10)."
  echo "#"
  echo "# Every entry declares a canonical plugin version for RHDH's {{inherit}}"
  echo "# keyword to resolve from CATALOG_INDEX_IMAGE. disabled: true on every entry"
  echo "# is deliberate — this index only declares versions; enabling a plugin for a"
  echo "# given tenant/operator stays their job in their own dynamic-plugins.yaml."
  echo "plugins:"
  for entry in "${sorted_entries[@]}"; do
    echo "  - package: ${entry}"
    echo "    disabled: true"
  done
} > "$OUTPUT"

echo "Generated dynamic-plugins.default.yaml: ${#sorted_entries[@]} entries, ${unique_images} unique images resolved"
