#!/usr/bin/env bash
#
# Seed committed per-workspace coverage snapshots onto the current default-branch
# (main) commit, so the Codecov default-branch view shows data for the
# workspaces already rolled out.
#
# Why this exists:
#   E2E coverage is only generated by the Prow e2e jobs, which deploy
#   INSTRUMENTED plugin images — and those images are only built by the PR
#   /publish flow (auto-publish-pr.yaml). So coverage is always uploaded
#   against a PR-head commit. When the PR is squash-merged, GitHub creates a
#   brand-new commit on main that never received an upload, and Codecov's
#   carryforward can't reach across the squash (the PR head is not an ancestor
#   of the squash commit). The result: every flag reads empty on main except
#   ones seeded by hand.
#
#   This script re-attributes the latest captured snapshot of each workspace's
#   coverage to the current main commit (scripts/upload-coverage.sh resolves
#   the SHA from GITHUB_SHA and the branch to main). It runs from
#   .github/workflows/seed-coverage-main.yaml on a schedule and whenever a
#   snapshot changes on main.
#
#   This is a bridge. The snapshot is a point-in-time capture (committed under
#   coverage-snapshots/<workspace>.lcov, refreshed by scripts/refresh-coverage-
#   snapshot.sh when a workspace's e2e runs), so the number only changes when
#   the snapshot is refreshed — which is also the only time the coverage itself
#   changes. The long-term replacement is live coverage from a main-attributed
#   Prow run (needs instrumented release images + an e2e-test-utils nightly
#   swap); see the repo README.
#
# Required environment:
#   CODECOV_TOKEN  - Codecov upload token (forwarded to upload-coverage.sh).
#   GITHUB_SHA     - Set by GitHub Actions to the default-branch HEAD.

set -euo pipefail

# Without a token, upload-coverage.sh warns and exits 0 for every workspace, so
# the job would go green while uploading nothing. Fail fast on the
# misconfiguration instead — for this upload-only job a missing token is a red X.
if [[ -z "${CODECOV_TOKEN:-}" && -z "${VAULT_CODECOV_TOKEN:-}" ]]; then
  echo "ERROR: no Codecov token (CODECOV_TOKEN / VAULT_CODECOV_TOKEN) — the seed would upload nothing. Set the CODECOV_TOKEN secret." >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SNAPSHOT_DIR="$REPO_ROOT/coverage-snapshots"

shopt -s nullglob
snapshots=("$SNAPSHOT_DIR"/*.lcov)
shopt -u nullglob

if [[ ${#snapshots[@]} -eq 0 ]]; then
  echo "[INFO] No coverage snapshots in $SNAPSHOT_DIR — nothing to seed."
  exit 0
fi

echo "=== Seeding ${#snapshots[@]} coverage snapshot(s) to the current main commit ==="
FAILED=0
for snapshot in "${snapshots[@]}"; do
  # The snapshot basename must equal a workspaces/<dir> name — it becomes the
  # Codecov flag (e2e-<ws>) and upload-coverage.sh validates the directory.
  ws="$(basename "$snapshot" .lcov)"
  echo ""
  echo "--- $ws (e2e-$ws) ---"
  if ! "$SCRIPT_DIR/upload-coverage.sh" "$ws" "$snapshot"; then
    echo "[WARN] Seed failed for $ws (non-fatal)"
    FAILED=$((FAILED + 1))
  fi
done

echo ""
echo "=== Done: $(( ${#snapshots[@]} - FAILED ))/${#snapshots[@]} seeded ==="
# A green run here means "dashboard updated". If every seed failed (e.g. all
# snapshots point at renamed/removed workspaces), that's a misconfiguration
# worth a red X, not a buried WARN.
[[ "$FAILED" -eq "${#snapshots[@]}" ]] && exit 1
exit 0
