apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-multi-source-security-viewer-backend
  namespace: community
  title: Multi Source Security Viewer Backend
  links:
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/multi-source-security-viewer
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/multi-source-security-viewer
  tags: []
spec:
  packageName: "@backstage-community/plugin-multi-source-security-viewer-backend"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-multi-source-security-viewer-backend:bs_1.49.4__0.4.1!backstage-community-plugin-multi-source-security-viewer-backend
  version: 0.4.1
  backstage:
    role: backend-plugin
    supportedVersions: 1.49.4
  author: Backstage Community
  support: community
  lifecycle: active
  appConfigNotRequired: true
  appConfigExamples: []
