apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: red-hat-developer-hub-backstage-plugin-intelligent-assistant-backend
  namespace: rhdh
  title: "Intelligent Assistant Backend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/intelligent-assistant/plugins/intelligent-assistant-backend
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/intelligent-assistant/plugins/intelligent-assistant-backend
  tags: []
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-intelligent-assistant-backend"
  dynamicArtifact: oci://quay.io/veecode/intelligent-assistant:bs_1.52.0!red-hat-developer-hub-backstage-plugin-intelligent-assistant-backend
  version: 3.2.0
  backstage:
    role: backend-plugin
    supportedVersions: 1.52.0
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - intelligent-assistant
  appConfigExamples:
    - title: Default configuration
      content:
        intelligent-assistant:
          # OPTIONAL: Port for intelligent-assistant service (default: 8080)
          servicePort: 8080
          # OPTIONAL: MCP server name and token for MCP servers defined in LCORE config
          # mcpServers:
          #  - name: <mcp server name>
          #    token: ${MCP_TOKEN}

          # OPTIONAL: Override default RHDH system prompt
          # systemPrompt: "You are a helpful assistant focused on Red Hat Developer Hub development."
