name: Publish DevPortal Dynamic Plugin Images
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'workspaces/**'
      - 'catalog-entities/**'
      - 'versions.json'

jobs:
  export:
    uses: veecode-platform/devportal-plugin-export-overlays/.github/workflows/publish-release-branch-workspace-plugins.yaml@main
    secrets:
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      QUAY_API_TOKEN: ${{ secrets.QUAY_API_TOKEN }}
    permissions:
      contents: write
      attestations: write
      packages: write
      id-token: write

  dispatch-docs-update:
    needs: export
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Trigger plugin catalog update in docs
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DOCS_DISPATCH_TOKEN }}
          repository: veecode-platform/docs
          event-type: plugin-catalog-update
