apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-rbac
  namespace: rhdh
  title: RBAC
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/rbac
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/rbac
  tags: []
spec:
  packageName: '@backstage-community/plugin-rbac'
  dynamicArtifact: ./dynamic-plugins/dist/backstage-community-plugin-rbac
  version: 1.52.4
  backstage:
    role: frontend-plugin
    supportedVersions: 1.49.4
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - rbac
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-rbac:
              translationResources:
                - importName: rbacTranslations
                  ref: rbacTranslationRef
                  module: Alpha
              appIcons:
                - name: rbacIcon
                  importName: RbacIcon
              dynamicRoutes:
                - path: /rbac
                  importName: RbacPage
                  menuItem:
                    icon: rbacIcon
                    text: RBAC
                    textKey: menuItem.rbac
              menuItems:
                rbac:
                  parent: default.admin
                  icon: rbacIcon
